version: '3'
networks:
  todoapp:
    driver: bridge

services:
  todolist:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todolist
    depends_on:
      - mysql
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      todoapp:

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql
    networks:
      todoapp:
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

